"""empty message

Revision ID: 862235edcc2f
Revises: 
Create Date: 2023-10-05 23:07:38.320857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862235edcc2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=25), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versao',
    sa.Column('tipo_sistema', sa.String(length=10), nullable=False),
    sa.Column('versao', sa.String(length=50), nullable=False),
    sa.Column('release', sa.String(length=50), nullable=False),
    sa.Column('dt_upload', sa.Date(), nullable=False),
    sa.Column('link_download', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('tipo_sistema', 'versao', 'release')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('autarquia', sa.String(length=50), nullable=False),
    sa.Column('nome_orgao_resp', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('ident_empresa', sa.String(length=4), nullable=False),
    sa.Column('situacao', sa.Integer(), nullable=False),
    sa.Column('tipo_sistema_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['tipo_sistema_id'], ['versao.tipo_sistema'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    op.drop_table('versao')
    op.drop_table('user')
    op.drop_table('responsavel')
    # ### end Alembic commands ###
